tasks:
  - command: |
      git submodule update --init --recursive --depth 1
      while [[ $(docker info > /dev/null; echo $?) != 0 ]]; do
          sleep 1
      done
      make container-image
      make container-serve
  - command: sudo docker-up
