image:
  file: .gitpod.Dockerfile
tasks:
  - init: git submodule update --init --recursive --depth 1
    command: |
      export HUGO_VERSION=$(grep ^HUGO_VERSION netlify.toml | tail -n 1 | cut -d '=' -f 2 | tr -d " \"\n")
      curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz | tar -xz
      ./hugo server --buildFuture --bind 0.0.0.0
